image: $CI_REGISTRY/smarts/smarts-dockerfiles/smarts-base

before_script:
  - /usr/bin/Xorg -noreset +extension GLX +extension RANDR +extension RENDER -logfile ./xdummy.log -config /etc/X11/xorg.conf -novtswitch $DISPLAY &
  - venv_dir=`mktemp -u -d`
  - python3.7 -m venv "${venv_dir}"
  - source "${venv_dir}/bin/activate"
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -e .
  - pip install -e .[train]

test:
  script:
    - make test

# Disabled until https://github.com/alphaville/optimization-engine/pull/206 is merged
# test-zoo:
#   script:
#     - make test-zoo

test-formatting:
  before_script:
    - pip install --upgrade pip
    - pip install black==19.10b0
    - apt-get update && apt-get install -y curl
    - curl -sL https://deb.nodesource.com/setup_14.x | bash -
    - apt-get install -y nodejs

  script: |
    black --check .
    npx prettier --check envision/web/src

test-requirements:
  script:
    ./test_pip_packages.sh

test-learning:
  script:
    make test-learning

  only:
    - master

test-benchmark:
  script: |
    apt-get update && apt-get -y install git
    git checkout $(git log --merges -n 1 --format=format:"%H")
    scl scenario build-all --clean ./scenarios
    pytest --benchmark-save=previous --benchmark-min-rounds=10 --benchmark-timer=time.process_time ./smarts/env/tests/test_benchmark.py

    git checkout -
    pip install -e .[train]
    scl scenario build-all --clean ./scenarios
    pytest --benchmark-compare=0001_previous --benchmark-compare-fail=mean:10% --benchmark-min-rounds=10 --benchmark-timer=time.process_time ./smarts/env/tests/test_benchmark.py

  except:
    - master
